version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV}
    restart: unless-stopped
    command: python /app/start.py
    volumes:
      - ${DATA_DIR}:/app/${DATA_DIR}
      - ${CONFIG_FILE}:/app/pytree.yml
    ports:
      - "${PORT}:${PORT}"
